### ISSUE TITLE
[Feature Request] Compatibility with popular illager mods

### ISSUE THREAD

**Issue by virtualonno** [Calculus-Master/DifficultRaids#11]
As noted in your mod's description, would you be willing to add raid compatibility with illager mods that add new raiders, such as:
- Savage & Ravage (https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage)
- It Takes a Pillage (https://www.curseforge.com/minecraft/mc-mods/it-takes-a-pillage)

**Comment by Calculus-Master** [comment]
Thanks for the suggestion! I was actually planning on adding compat for Savage & Ravage, It Takes a Pillage and Illage & Spillage since they're the largest illager mods I know of – that will probably be happening after I rework how the waves are set up.

If you know of any other mods please let me know!

**Comment by Calculus-Master** [comment]
Latest update adds Savage & Ravage, Illage & Spillage, and Dungeon Mobs, and It Takes a Pillage was added in v2.0.beta.2
