### ISSUE TITLE
raid wave count bug

### ISSUE THREAD

**Issue by TheMicrowave1024** [Calculus-Master/DifficultRaids#15]
very confusing bug
wave count is (config + 1)
display count is normal
no upper bound = index out of bound crash

[suggestion] make wave count default to 8 because magi

**Comment by Calculus-Master** [comment]
Thanks for the report – can you share what your datapack looks like? Also I'm not understanding what you mean by "no upper bound = index out of bound crash", can you explain it a bit more?

**Comment by TheMicrowave1024** [comment]
no datapack were used
and
if u set the wave number to be larger than 8 or something the game crashes

**Comment by Calculus-Master** [comment]
Ah, I see what you mean. I'll look into why it crashes with more waves. If you have a crash report that would be helpful!

Regarding the "wave count is config + 1", that's actually the bonus wave spawning. I don't recall how it triggers in raids (i think it's based on bad omen levels?) but as it stands now the bonus wave is always going to spawn. I'm planning to take a look at it later and add a deterministic way to trigger it.

**Comment by Calculus-Master** [comment]
Alright, I believe I've fixed this issue. There's a couple other things I'm finishing up with the next version before it'll go live on CF. Thanks for bringing my attention to the problem!

Also, if you're going to use larger wave counts, there's a config option that you need to change if you don't edit any spawns using datapacks. It's called "arrayOverflowMode" (in the general.toml, should be near the top), and you'll want to set it to "REPEAT", otherwise the spawn amounts will be 0. The config option explains how the two modes work, but if its confusing feel free to ask and I can explain more.

**Comment by TheMicrowave1024** [comment]
thanks
