### ISSUE TITLE
Worker-ResourceReload-5/ERROR

### ISSUE THREAD

**Issue by Krimatoria** [Calculus-Master/DifficultRaids#20]
Red Error
difficultraids-1.19.2-2.0-beta.11.jar
[04:10:58] [Worker-ResourceReload-5/ERROR]: Using missing texture, unable to load difficultraids:mob_effect/winds_curse

**Comment by Calculus-Master** [comment]
Thanks for the report! There isn't a texture for the effect as of now, so it'll throw that error because it can't find one. A texture is definitely planned, just not in yet. It shouldn't affect anything in game, you'll just see some purple and black squares (instead of traditional potion bubbles) when that effect is applied to you.

**Comment by Krimatoria** [comment]
> Спасибо за отчет! На данный момент текстуры для эффекта не существует, поэтому он выдаст эту ошибку, поскольку не может ее найти. Текстура определенно запланирована, но еще не создана. Это не должно ни на что влиять в игре, вы просто увидите несколько фиолетовых и черных квадратов (вместо традиционных пузырей с зельями), когда к вам применится этот эффект.

Ok)))
